### PR TITLE
add white-space nowrap for .starr class

### PR DESCRIPTION
**Pull request by adam187**
to keep starts in single line

### CODE REVIEW

**Comment by ajb** [comment]
Thanks for the PR! Can you show me an example of when the stars would wrap, and why that would happen?

**Comment by adam187** [comment]
@ajb In my case this issue occurred in table cell.

Here is example of issue:
http://jsbin.com/mobaji/2/

**Comment by ajb** [comment]
Ah, thank you, that makes sense. I think in the case of a star rating
inside of a table, it's appropriate to simply add the additional CSS rule
in your application instead of in starrr itself. Does that work for you?

On Thu, May 14, 2015 at 10:13 AM, Adam Misiorny notifications@github.com
wrote:

> @ajb https://github.com/ajb In my case this issue occurred in table
> cell.
> 
> Here is example of issue:
> http://jsbin.com/mobaji/2/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dobtco/starrr/pull/6#issuecomment-102048095.

## 

Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by adam187** [comment]
@cjoh Sure, i already fixed it in my project but i thought it might be helpful for other users.

**Pull request closed without merging**
